[project_cfg]
name = "NftAuction"

[server]
port = ":80"
max_num = 500

[log]
compress = false
keep_days = 7
level = "info"
mode = "console"
path = "logs/v1-backend"
service_name = "v1-backend"

[db]
database = "xxx"
password = "xxx"
port = 123
max_open_conns = 1500
host = "127.0.0.1"
log_level = "info"
max_conn_max_lifetime = 300
user = "xxx"
max_idle_conns = 10

[eth]
rpc_url = "https://infura.io..."
chain_id = 123456
auction_addr = "0x111111"
batch_size = 10
block_delay = 6
